// Auto-generated by deploy.js — do not edit manually
// This file is updated automatically after each deployment
const contractConfig = {
  afCoinAddress: "0xb518Ff71b149Bcb9831334414D46094dff96bB89",
  afcIcoAddress: "0x940b6759287B44Ed69f5720Fb65be3c01A7793Bc",
};

export default contractConfig;
