const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // 1) Deploy the AfCoin token
  const initialSupply = hre.ethers.utils.parseEther("1000"); // 1,000 tokens
  const AfCoin = await hre.ethers.getContractFactory("AfCoin");
  const afCoin = await AfCoin.deploy(initialSupply);
  await afCoin.deployed();
  console.log("AfCoin deployed to:", afCoin.address);

  // 2) Configure a 5-month window
  const now        = Math.floor(Date.now() / 1000);
  const startTime  = now + 60;
  const fiveMonths = 5 * 30 * 24 * 60 * 60;
  const endTime    = startTime + fiveMonths;

  const rate   = 1000;
  const wallet = deployer.address;

  // 3) Deploy the ICO
  const AfCoinICO = await hre.ethers.getContractFactory("AfCoinICO");
  const ico = await AfCoinICO.deploy(
    afCoin.address,
    rate,
    startTime,
    endTime,
    wallet
  );
  await ico.deployed();
  console.log("AfCoinICO deployed to:", ico.address);
  console.log("Sale window:", startTime, "→", endTime);

  // 4) Auto-update the frontend contract config file
  const configPath = path.join(__dirname, "..", "afc-website", "resources", "js", "contractConfig.js");
  const configContent = `// Auto-generated by deploy.js — do not edit manually
// This file is updated automatically after each deployment
const contractConfig = {
  afCoinAddress: "${afCoin.address}",
  afcIcoAddress: "${ico.address}",
};

export default contractConfig;
`;
  fs.writeFileSync(configPath, configContent);
  console.log("Updated contractConfig.js with new addresses.");

  // 5) Auto-update index.html (standalone HTML file)
  const indexPath = path.join(__dirname, "..", "index.html");
  if (fs.existsSync(indexPath)) {
    let indexContent = fs.readFileSync(indexPath, "utf8");
    indexContent = indexContent.replace(
      /const contractAddress = \"[0-9a-fA-Fx]+\"/,
      `const contractAddress = \"${afCoin.address}\"`
    );
    fs.writeFileSync(indexPath, indexContent);
    console.log("Updated index.html with new address.");
  }

  // 6) Auto-update scripts/sendAFC.js
  const sendAfcPath = path.join(__dirname, "sendAFC.js");
  if (fs.existsSync(sendAfcPath)) {
    let sendAfcContent = fs.readFileSync(sendAfcPath, "utf8");
    sendAfcContent = sendAfcContent.replace(
      /const tokenAddress = \"[0-9a-fA-Fx]+\"/,
      `const tokenAddress = \"${afCoin.address}\"`
    );
    fs.writeFileSync(sendAfcPath, sendAfcContent);
    console.log("Updated sendAFC.js with new address.");
  }
}

main().catch(err => {
  console.error(err);
  process.exitCode = 1;
});
